substitutions:
  name: kitchen

esphome:
  name: aspirator
  friendly_name: Aspirator
  project:
    name: simovis.aspirator_3_speed+light
    version: "1.2"
  min_version: 2025.10.0

bk72xx:
  board: cb3s

logger:

api:
  encryption:
    key: 

ota:
  - platform: esphome
    password: 

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Aspirator Fallback Hotspot"
    password: 

captive_portal:

# -----------------------------
#  STATUS INFO
# -----------------------------
text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP Address"
    ssid:
      name: "Connected SSID"
    mac_address:
      name: "MAC Address"
  - platform: version
    name: "ESPHome Version"

# -----------------------------
#  BUTTONS
# -----------------------------
binary_sensor:
  - platform: gpio
    id: button_speed_1
    pin: 
      number: 26
      inverted: true
      mode:
        input: true
        pullup: true
    filters:
      - delayed_on_off: 10ms
    on_press:
      - script.execute: set_speed_1

  - platform: gpio
    id: button_speed_2
    pin:
      number: 11
      inverted: true
      mode:
        input: true
        pullup: true
    filters:
      - delayed_on_off: 10ms
    on_press:
      - script.execute: set_speed_2

  - platform: gpio
    id: button_speed_3
    pin:
      number: 14
      inverted: true
      mode:
        input: true
        pullup: true
    filters:
      - delayed_on_off: 10ms
    on_press:
      - script.execute: set_speed_3

  - platform: gpio
    id: button_light
    pin: 
      number: 22
      inverted: true
      mode:
        input: true
        pullup: true
    filters:
      - delayed_on_off: 20ms
    on_press:
      - switch.toggle: lightfan

# -----------------------------
#  FAN SPEED CONTROL (Slider)
# -----------------------------
number:
  - platform: template
    name: "Fan $name Speed"
    id: fanspeed
    icon: mdi:fan
    update_interval: never
    optimistic: true
    min_value: 1
    max_value: 3
    step: 1
    on_value:
      then:
        - script.execute: apply_speed

# -----------------------------
#  SCRIPTS
# -----------------------------
script:
  # Centralni handler koji postavlja releje prema brzini
  - id: apply_speed
    then:
      - if:
          condition:
            switch.is_on: master
          then:
            - lambda: |-
                int spd = (int) id(fanspeed).state;
                id(relay1).turn_off();
                id(relay2).turn_off();
                id(relay3).turn_off();
                if (spd == 1) id(relay1).turn_on();
                if (spd == 2) id(relay2).turn_on();
                if (spd == 3) id(relay3).turn_on();

  - id: set_speed_1
    then:
      - if:
          condition:
            and:
              - lambda: 'return id(fanspeed).state == 1;'
              - switch.is_on: master
          then:
            - switch.turn_off: master
          else:
            - number.set: 
                id: fanspeed
                value: 1
            - switch.turn_on: master

  - id: set_speed_2
    then:
      - if:
          condition:
            and:
              - lambda: 'return id(fanspeed).state == 2;'
              - switch.is_on: master
          then:
            - switch.turn_off: master
          else:
            - number.set: 
                id: fanspeed
                value: 2
            - switch.turn_on: master

  - id: set_speed_3
    then:
      - if:
          condition:
            and:
              - lambda: 'return id(fanspeed).state == 3;'
              - switch.is_on: master
          then:
            - switch.turn_off: master
          else:
            - number.set: 
                id: fanspeed
                value: 3
            - switch.turn_on: master

# -----------------------------
#  SWITCHES (RELAYS)
# -----------------------------
switch:
  - platform: template
    id: master
    name: "Fan $name Master"
    icon: mdi:fan
    optimistic: true
    on_turn_on:
      - script.execute: apply_speed
    on_turn_off:
      - lambda: |-
          id(relay1).turn_off();
          id(relay2).turn_off();
          id(relay3).turn_off();

  - platform: gpio
    name: "$name Fan Speed 1"
    id: relay1
    icon: mdi:fan-speed-1
    pin: 7
    interlock: &interlock_group [relay1, relay2, relay3]
    interlock_wait_time: 200ms

  - platform: gpio
    name: "$name Fan Speed 2"
    id: relay2
    icon: mdi:fan-speed-2
    pin: 10
    interlock: *interlock_group
    interlock_wait_time: 200ms

  - platform: gpio
    name: "$name Fan Speed 3"
    id: relay3
    icon: mdi:fan-speed-3
    pin: 20
    interlock: *interlock_group
    interlock_wait_time: 200ms

  - platform: gpio
    name: "Fan Light $name"
    icon: mdi:lightbulb
    id: lightfan
    pin: 23
